### PR TITLE
Fix path weirdness

### PR DESCRIPTION
**Pull request by michquinn**

### CODE REVIEW

**Review by FlatBallFlyer — CHANGES_REQUESTED** [review]
Wow - IMHO that seems to have introduced a lot of complications for what was a minor weirdness.... before we merge this, can you look into use the ``WORKING_DIR`` property in the Dockerfile (or some other alternative?) - something that says "run entrypoint.sh from this folder" - that seems like it would be a much cleaner approach to the problem.

**Comment by michquinn** [comment]
I don't quite understand your concerns here (other than the Dockerfile, which I'll look into updating later), nor what you mean by "complications". This allows you to run the script from anywhere - the paths are now all relative to the mongosh directory rather than whatever your working directory happens to be, which I think is much cleaner and more logical.

Not all changes made here were necessarily essential, like using path.join, though I also felt that was cleaner than string concatenation.

**Comment by FlatBallFlyer** [comment]
What I meant was you changed 7 files, adding a layer of abstraction to each, all to avoid running a test.sh script from a specific folder. Seems excessive to me. Look into the Dockerfile solution, I think that will allow you to make a 1-line change, and make all of those other changes un-necessary.

**Comment by FlatBallFlyer** [comment]
one alternative might be to do the ``cd`` command in the docker compose - 
```
 entrypoint: ["cd ./mongosh; ./entrypoint.sh"]
```
but the best way will be to add
```
WORKDIR /mongosh
```
line to the Dockerfile - then remove the cd command from entrypoint.sh
then change the readme to use ./test.sh from the mongosh folder.

It may also be a good idea to set entrypoint for the container at build time, and avoid having to include it in the docker compose file. 

While we are at it, can we maybe provide "default" values for environment variables in the Dockerfile, and remove them from docker-compose - we can over-ride in a compose file if needed, but if we can have meaningful default values that would be awesome.

**Comment by FlatBallFlyer** [comment]
# Pseudo-code 

## mongdb Dockerfile
```docker
# From MongoDB Offical Image
FROM mongo:latest

# Copy files in
WORKDIR /mongosh
COPY ./src/mongosh .

# Set Deafault ENV Values
ENV HOST=mentorhub-mongodb
ENV AUTH_DB=admin
ENV DB_NAME=agile-learning-institute
ENV LOAD_TEST=true

# Specify the entrypoint
ENTRYPOINT [ "entrypoint.sh" ]
```

## docker-compose.yaml mentorhub-mongosh service
```docker
  mentorhub-mongosh:
    image: ghcr.io/agile-learning-institute/mentorhub-mongosh:latest
    depends_on:
      mentorhub-mongodb:
        condition: service_healthy
    environment:
      - USER=root
      - PASSWORD=example
    profiles:
      - db
      - person
      - person-api
```

**Comment by michquinn** [comment]
How's this? It's a much lighter approach that, as far as I can tell (including tests I've just run), works exactly the same https://github.com/agile-learning-institute/mentorHub-mongodb/commit/4818edb86095db1419c977e31b615a8f38735317

**Pull request closed without merging**
