### PR TITLE
Create initial proposal for new Topics schema

### PR DESCRIPTION
**Pull request by michquinn**
Alternative enumeration values for `mediaType`: `text`, `audio`, `video-only`, `video-with-audio`. I also like Graham's suggestion of `interactive` (that may cover the `tool` category as well)

I also started to draft a curriculum schema but thought it might be out of scope for this PR. Still, it helped me think about how resources and topics may be used so I'll include it here:

```json
{
	"description": "A curriculum",
	"bsonType": "object",
	"required": ["name"],
	"properties": {
		"apprentice_id": {
			"description": "ID of the Apprentice this curriculum belongs to",
			"bsonType": "string"
		},
		"resumeGoals": {
			"description": "The list of Skills related to this topic",
			"bsonType": "array",
			"items": { "bsonType": "string" }
		},
		"resources": {
			"bsonType": "array",
			"items": {
				"bsonType": "object",
				"properties": {
					"name": { "bsonType": "string" },
					"started": { "bsonType": "Date" },
					"completed": { "bsonType": "Date" },
					"scope": { "bsonType": "string", "enum": [ "Celebrated", "Now", "Next", "Later" ] }
				}
			}
		}
	}
}
```

I was planning to write up a justification for various aspects of the design, may add that soon.

I haven't edited the scraper scripts yet

### CODE REVIEW

**Comment by FlatBallFlyer** [comment]
Here are my thoughts, in no particular order. 
- In the topic schema
  - We need a description for "partOfSeries"
  - what happened to the domain attribute?
  - I think the skills and resources arrays should be of type objectId - see [this article](https://www.mongodb.com/developer/products/mongodb/mongodb-schema-design-best-practices/) for schema design best practices. 
  - I'm not sure that these arrays are the best choice, we can put a topic id in the skill/resource collection as an alternative
 
- enumerators collection
  - The idea of this collection is to support a single GET to get all of the enumerators that a UI might need for "select" or other features. We need to add that to the README so it's more clear. I also shared ideas with you about how to restructure that so that it is the single source of truth for enumerator meanings. 
  - please add or update all of the appropriate arrays in the enumerators data file

- resources schema
  - I believe tags should be a enumerator
  - can we have some data quality constraints to duration
  - can we add a pattern constraint to the link to ensure that it's a proper HTTP link
  - I think free would be better represented as a tag than a Boolean

- skills schema
  - please split line breaks so this is more similar to YAML - one attribute/value per line
  - we need appropriate constraints on all properties
  - we also need a description for partOfSeries, I thought maybe it was an alternative to domain, but you have both in this schema

As a housekeeping item, you can remove the institute- prefix on all of the files and replace it with a mentorHub- prefix. Note this will require code changes in migrate.js

PS: Do we need a "rating" value for a resource? Members will provide reviews, but it might be best to keep a running rating value in the resource to avoid doing a fetch-to-count operation when getting resource information.

**Comment by michquinn** [comment]
> Here are my thoughts, in no particular order.
> 
> * In the topic schema
>       
>     * We need a description for "partOfSeries"
>     * what happened to the domain attribute?
>
> […]
>
> * skills schema
>   * we also need a description for partOfSeries, I thought maybe it was an alternative to domain, but you have both in this schema

The original Topic domain field (the EngineerKit categories such as Architecture, Infrastructure, etc.) has  been removed. Replacing it is `partOfSeries`, which is not a direct equivalent. This property provides a means to preserve the course or curriculum which this topic forms a part of.

The domain for classifications of the form `Specialist-SRE` was moved to the skills schema.

> I think the skills and resources arrays should be of type objectId - see [this article](https://www.mongodb.com/developer/products/mongodb/mongodb-schema-design-best-practices/) for schema design best practices.

I agree, I didn't know how to write that at the time. This will be updated.

> * enumerators collection
>
>   * The idea of this collection is to support a single GET to get all of the enumerators that a UI might need for "select" or other features. We need to add that to the README so it's more clear. I also shared ideas with you about how to restructure that so that it is the single source of truth for enumerator meanings.

I'm not sure if you had this in mind but be aware that for schema validation purposes, MongoDB doesn't support JSON references or similar embedding (see https://www.mongodb.com/docs/manual/reference/operator/query/jsonSchema/#std-label-json-schema-omission)

**Comment by michquinn** [comment]
> * In the topic schema
>       
>   * I'm not sure that these arrays are the best choice, we can put a topic id in the skill/resource collection as an alternative

For skills that's fine, but it seems it would be necessary to keep an array of resources for each topic in order to support the Topic API as described here https://github.com/agile-learning-institute/mentorHub-topic-api/issues/2

**Comment by michquinn** [comment]
> * resources schema
>   * I think free would be better represented as a tag than a Boolean

What do you think of an enum along the following lines?
```json
{
	"properties": {
		"meansOfAccess": {
			"bsonType": "string",
			"enum": [ "free-public", "free-account", "pay" ]
		}
	}
}
```

**Comment by FlatBallFlyer** [comment]
# One to Many relationships
re: topic -> skills and topic -> resources We should handle both of the relationships in the same way. We have two options here, and one is actually many-to-many.

## Option 1 - pure one-to-many
- Topic has no reference to skills or resources
- Skills and Resources have a topicId
- When querying the topic a lookup where skills.topicId == topic._id

## Option 2 - many-to-many
- Topic has arrays of SkillId and ResourceId ``resources:[resourceId], skills:[skillId]``
- Skills and resources have no reference to Topic
- When querying the topic a lookup where resource._id in topic.resources

After some research I believe Option 2 may be superior performance wise. The API can support either approach without impacting anything there. I do think we missed skills endpoints that mimic the resources endpoints. 

# meansOfAccess
Why is this a new attribute? I would prefer that we add those enumerated values to a more generic tags attribute. I'm not overly concerned about enforcing mutuall exclusivity constraints, and using a single tags attribute to deal with a variety of properties is very flexible.

**Comment by michquinn** [comment]
Resolved by #79

**Pull request closed without merging**
