### PR TITLE
Refine link validation

### LINKED ISSUE #99: Fix link validation
Currently, links are validated with the following regular expression
https://github.com/agile-learning-institute/mentorHub-mongodb/blob/9dc5ea5ec8b499ac7c9dacc2754a7cc02a44597d/src/mongosh/schemas/resources-1.0.2.json#L43
After some discussion and uncertainty about the intended meaning of this expression, it was resolved that a new pattern should be created. On the basis of [RFC 3986](https://www.rfc-editor.org/rfc/rfc3986.html#appendix-A) (primarily), I propose this pattern:
```
^https:\/\/([a-zA-Z0-9-]{1,63}\.)+[a-zA-Z-]{2,24}(:[0-9]{1,5})?(\/(([\w\-\.~]|%[a-fA-F0-9]{2}|[!\$&'\(\)\*\+,;=:@])*\/?)*)?
```
The intention is as follows:
1. `scheme` must be `https`
2. The host name (here meaning everything that appears before the top-level domain such as `.com`) may consist of a series of one or more strings ranging from 1-63 characters (alphanumeric or a hyphen) separated by a period, with the upper limit coming from RFC 1035 
3. A top-level domain of 2-24 characters, the upper limit corresponding to the longest existing gTLD as of this writing (character may be alphanumeric or a hyphen, the latter allowing support for non-Latin-script gTLDs via "punycode")
4. An optional port number (1-5 decimal characters), which must be preceded by a colon
5. If there is more to the URI, it must start with a slash `/`
6. Following the slash, 0 or more of the following may appear:
    - An unreserved character, defined as a letter, digit, `-`, `.`, `_`, or `~`. Note that the escape sequence `\w` is equivalent to `[a-zA-Z0-9_]`
    - A percent-encoded character (`%` followed by a two-digit hexadecimal number)
    - `sub-delims`, an additional set of permitted non-alphanumeric characters

### PR DESCRIPTION
**Pull request by michquinn**
Closes #99

### CODE REVIEW

**Review by MyNameIsAndrew-Mangix — APPROVED** [review]
Super thorough and flexible regex that took me a long time to learn what it did xd.

**Review by FlatBallFlyer — CHANGES_REQUESTED** [review]
I like this change but....
- You need to update the ``config/resources.json`` to reference the new version
- Running ``test.sh`` from ``src/mongosh`` shows the error about schema not found 
- Running ``./src/docker/docker-build.sh`` and looking at the container output shows the same error.
- vsCode says ``Invalid escape character in string.json(261)``
- When I fix the version number, running ``test.sh`` shows  ``SyntaxError: /Users/mikestorey/source/agile-learning-institute/mentorHub-mongodb/src/mongosh/schemas/resources-1.0.3.json: Bad escaped character in JSON at position 1025 (line 43 column 47)
``

**Comment by michquinn** [comment]
JSON strings require both forward and backslashes to be escaped, independently of the escapes needed for the regex. The change has been made, but the string must be unescaped now to produce a valid regex

**Comment by MyNameIsAndrew-Mangix** [comment]
I should've tested, mb. It looked fine but I guess the change had unexpected side-effects. The JSON escape fix worked both locally and in the container for me without issues

**Review by FlatBallFlyer — APPROVED** [review]

**Pull request merged**
